#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jun 24 20:10:44 2017
@author: wroscoe
remotes.py
The client and web server needed to control a car remotely.
"""


import os
import json
import logging
import math
import time
import asyncio

import requests
from tornado.ioloop import IOLoop
from tornado.web import Application, RedirectHandler, StaticFileHandler, \
    RequestHandler
from tornado.httpserver import HTTPServer
import tornado.gen
import tornado.websocket
from socket import gethostname

from ... import utils

logger = logging.getLogger(__name__)


def _default_tuning():
    return {
        'hsv_center_low':  [0, 0, 0],
        'hsv_center_high': [179, 255, 255],
        'hsv_edge_low':    [0, 0, 0],
        'hsv_edge_high':   [179, 255, 255],
        'pid_p': 0.0, 'pid_i': 0.0, 'pid_d': 0.0,
        'throttle_min': 0.0, 'throttle_max': 1.0,
        'scan_y': 0, 'scan_height': 0,
        'steering_left_pwm': 0, 'steering_right_pwm': 0,
    }


def _clamp(v, lo, hi):
    return max(lo, min(hi, v))


def _validate_tuning_patch(patch, current):
    """
    Sanitize a {key: value} patch against the current tuning dict.
    Returns (clean_patch, rejections) where rejections is a list of
    {key, reason} for keys that were dropped or clamped.

    Validation rules:
      - HSV arrays: length-3 ints. H clamped to 0..179, S/V to 0..255.
      - pid_p/i/d: finite floats with |v| <= 10.
      - throttle_min/max: finite floats clamped to -1..1; if both present,
        min must be <= max (rejected if not).
      - scan_y / scan_height: non-negative ints (upper bound not enforced
        here; LineFollower clips at frame height).
    Unknown keys are dropped.
    """
    clean = {}
    rejections = []
    hsv_keys = ('hsv_center_low', 'hsv_center_high',
                'hsv_edge_low',   'hsv_edge_high')
    pid_keys = ('pid_p', 'pid_i', 'pid_d')

    def reject(k, reason):
        rejections.append({'key': k, 'reason': reason})

    for k, v in (patch or {}).items():
        try:
            if k in hsv_keys:
                if not (isinstance(v, (list, tuple)) and len(v) == 3):
                    reject(k, 'expected length-3 array')
                    continue
                h, s, val = int(v[0]), int(v[1]), int(v[2])
                clean[k] = [_clamp(h, 0, 179),
                            _clamp(s, 0, 255),
                            _clamp(val, 0, 255)]
            elif k in pid_keys:
                fv = float(v)
                if not math.isfinite(fv) or abs(fv) > 10:
                    reject(k, 'not finite or |v|>10')
                    continue
                clean[k] = fv
            elif k in ('throttle_min', 'throttle_max'):
                fv = float(v)
                if not math.isfinite(fv):
                    reject(k, 'not finite')
                    continue
                clean[k] = _clamp(fv, -1.0, 1.0)
            elif k in ('scan_y', 'scan_height'):
                iv = int(v)
                if iv < 0:
                    reject(k, 'negative')
                    continue
                clean[k] = iv
            elif k in ('steering_left_pwm', 'steering_right_pwm'):
                iv = int(v)
                # PCA9685 12-bit values: 0..4095. Reject anything outside.
                if not (0 <= iv <= 4095):
                    reject(k, 'out of range 0..4095')
                    continue
                clean[k] = iv
            else:
                reject(k, 'unknown key')
        except (TypeError, ValueError) as exc:
            reject(k, f'parse error: {exc}')

    # Cross-key invariant: throttle_min <= throttle_max
    new_min = clean.get('throttle_min', current.get('throttle_min', 0.0))
    new_max = clean.get('throttle_max', current.get('throttle_max', 1.0))
    if new_min > new_max:
        if 'throttle_min' in clean:
            reject('throttle_min', 'would exceed throttle_max')
            clean.pop('throttle_min')
        if 'throttle_max' in clean:
            reject('throttle_max', 'would fall below throttle_min')
            clean.pop('throttle_max')

    return clean, rejections


def _render_myconfig_snippet(t):
    """Render the current tuning dict as Python suitable for myconfig.py."""
    def tup(arr):
        return '(' + ', '.join(str(int(x)) for x in arr) + ')'
    lines = [
        '# === Auto-generated by web tuning panel ===',
        f'COLOR_THRESHOLD_LOW       = {tup(t["hsv_center_low"])}',
        f'COLOR_THRESHOLD_HIGH      = {tup(t["hsv_center_high"])}',
        f'EDGE_COLOR_THRESHOLD_LOW  = {tup(t["hsv_edge_low"])}',
        f'EDGE_COLOR_THRESHOLD_HIGH = {tup(t["hsv_edge_high"])}',
        f'PID_P = {t["pid_p"]!r}',
        f'PID_I = {t["pid_i"]!r}',
        f'PID_D = {t["pid_d"]!r}',
        f'THROTTLE_MIN = {t["throttle_min"]!r}',
        f'THROTTLE_MAX = {t["throttle_max"]!r}',
        f'SCAN_Y = {int(t["scan_y"])}',
        f'SCAN_HEIGHT = {int(t["scan_height"])}',
        '',
        '# Update these inside the PWM_STEERING_THROTTLE dict in myconfig.py:',
        f'#   "STEERING_LEFT_PWM":  {int(t["steering_left_pwm"])},',
        f'#   "STEERING_RIGHT_PWM": {int(t["steering_right_pwm"])},',
        '',
    ]
    return '\n'.join(lines)


class RemoteWebServer():
    '''
    A controller that repeatedly polls a remote webserver and expects
    the response to be angle, throttle and drive mode.
    '''

    def __init__(self, remote_url, connection_timeout=.25):

        self.control_url = remote_url
        self.time = 0.
        self.angle = 0.
        self.throttle = 0.
        self.mode = 'user'
        self.mode_latch = None
        self.recording = False
        # use one session for all requests
        self.session = requests.Session()

    def update(self):
        '''
        Loop to run in separate thread the updates angle, throttle and
        drive mode.
        '''

        while True:
            # get latest value from server
            self.angle, self.throttle, self.mode, self.recording = self.run()

    def run_threaded(self):
        '''
        Return the last state given from the remote server.
        '''
        return self.angle, self.throttle, self.mode, self.recording

    def run(self):
        '''
        Posts current car sensor data to webserver and returns
        angle and throttle recommendations.
        '''

        data = {}
        response = None
        while response is None:
            try:
                response = self.session.post(self.control_url,
                                             files={'json': json.dumps(data)},
                                             timeout=0.25)

            except requests.exceptions.ReadTimeout as err:
                print("\n Request took too long. Retrying")
                # Lower throttle to prevent runaways.
                return self.angle, self.throttle * .8, None

            except requests.ConnectionError as err:
                # try to reconnect every 3 seconds
                print("\n Vehicle could not connect to server. Make sure you've " +
                    "started your server and you're referencing the right port.")
                time.sleep(3)

        data = json.loads(response.text)
        angle = float(data['angle'])
        throttle = float(data['throttle'])
        drive_mode = str(data['drive_mode'])
        recording = bool(data['recording'])

        return angle, throttle, drive_mode, recording

    def shutdown(self):
        pass


class LocalWebController(tornado.web.Application):

    def __init__(self, port=8887, mode='user'):
        """
        Create and publish variables needed on many of
        the web handlers.
        """
        logger.info('Starting Donkey Server...')

        this_dir = os.path.dirname(os.path.realpath(__file__))
        self.static_file_path = os.path.join(this_dir, 'templates', 'static')
        self.angle = 0.0
        self.throttle = 0.0
        self.mode = mode
        self.mode_latch = None
        self.recording = False
        self.recording_latch = None
        self.buttons = {}  # latched button values for processing

        # Runtime-tunable parameters surfaced to the web UI (HSV, PID,
        # throttle, scan region). Seed defaults; manage.py overwrites these
        # from cfg at boot. Mutations come from /wsTuning.
        self.tuning = _default_tuning()
        self.tuning_seq = 0
        self.tuning_listeners = []  # list[Callable[[dict], None]]
        self.wsTuningClients = []

        self.port = port

        self.num_records = 0
        self.wsclients = []
        self.loop = None


        handlers = [
            (r"/", RedirectHandler, dict(url="/drive")),
            (r"/drive", DriveAPI),
            (r"/wsDrive", WebSocketDriveAPI),
            (r"/wsCalibrate", WebSocketCalibrateAPI),
            (r"/wsTuning", WebSocketTuningAPI),
            (r"/tuning/snippet", TuningSnippetHandler),
            (r"/tuning/state", TuningStateHandler),
            (r"/calibrate", CalibrateHandler),
            (r"/video", VideoAPI),
            (r"/wsTest", WsTest),

            (r"/static/(.*)", StaticFileHandler,
             {"path": self.static_file_path}),
        ]

        settings = {'debug': True}
        super().__init__(handlers, **settings)
        logger.info(f"You can now go to {gethostname()}.local:{port} to "
                    f"drive your car.")

    def update(self):
        """ Start the tornado webserver. """
        asyncio.set_event_loop(asyncio.new_event_loop())
        self.listen(self.port)
        self.loop = IOLoop.instance()
        self.loop.start()

    def update_wsclients(self, data):
        if data:
            for wsclient in self.wsclients:
                try:
                    data_str = json.dumps(data)
                    logger.debug(f"Updating web client: {data_str}")
                    wsclient.write_message(data_str)
                except Exception as e:
                    logger.warning("Error writing websocket message",
                                   exc_info=e)
                    pass

    def apply_tuning_patch(self, patch, origin=None):
        """
        Validate, commit, and broadcast a tuning patch. Invokes registered
        tuning_listeners with the full snapshot. Returns the rejections list.

        `origin`, when set, is the WebSocket handler that sent the patch;
        the broadcast skips it so a slider drag doesn't echo back and
        snap the live drag handle to the just-committed value.
        """
        clean, rejections = _validate_tuning_patch(patch, self.tuning)
        logger.info("[tuning] apply_patch in=%s clean=%s rej=%s",
                    list(patch.keys()), list(clean.keys()),
                    [r['key'] for r in rejections])
        if clean:
            self.tuning.update(clean)
            self.tuning_seq += 1
            logger.info("[tuning] listeners=%d about to fire",
                        len(self.tuning_listeners))
            for listener in self.tuning_listeners:
                try:
                    listener(self.tuning)
                except Exception as e:
                    logger.warning("Tuning listener raised", exc_info=e)
            self.broadcast_tuning(skip=origin)
        return rejections

    def broadcast_tuning(self, skip=None):
        msg = json.dumps({'type': 'snapshot',
                          'tuning': self.tuning,
                          'seq': self.tuning_seq})
        for client in list(self.wsTuningClients):
            if client is skip:
                continue
            try:
                client.write_message(msg)
            except Exception as e:
                logger.warning("Error writing tuning ws message", exc_info=e)

    def run_threaded(self, img_arr=None, num_records=0, mode=None, recording=None):
        """
        :param img_arr: current camera image or None
        :param num_records: current number of data records
        :param mode: default user/mode
        :param recording: default recording mode
        """
        self.img_arr = img_arr
        self.num_records = num_records

        #
        # enforce defaults if they are not none.
        #
        changes = {}
        if mode is not None and self.mode != mode:
            self.mode = mode
            changes["driveMode"] = self.mode
        if self.mode_latch is not None:
            self.mode = self.mode_latch
            self.mode_latch = None
            changes["driveMode"] = self.mode
        if recording is not None and self.recording != recording:
            self.recording = recording
            changes["recording"] = self.recording
        if self.recording_latch is not None:
            self.recording = self.recording_latch;
            self.recording_latch = None;
            changes["recording"] = self.recording;

        # Send record count to websocket clients
        if (self.num_records is not None and self.recording is True):
            if self.num_records % 10 == 0:
                changes['num_records'] = self.num_records

        #
        # get latched button presses then clear button presses
        # Next iteration will clear press in memory
        #
        buttons = self.buttons
        self.buttons = {}
        for button, pressed in buttons.items():
            if pressed:
                self.buttons[button] = False

        # if there were changes, then send to web client
        if changes and self.loop is not None:
            logger.debug(str(changes))
            self.loop.add_callback(lambda: self.update_wsclients(changes))

        return self.angle, self.throttle, self.mode, self.recording, buttons

    def run(self, img_arr=None, num_records=0, mode=None, recording=None):
        return self.run_threaded(img_arr, num_records, mode, recording)

    def shutdown(self):
        pass


class DriveAPI(RequestHandler):

    def get(self):
        data = {}
        self.render("templates/vehicle.html", **data)

    def post(self):
        '''
        Receive post requests as user changes the angle
        and throttle of the vehicle on a the index webpage
        '''
        data = tornado.escape.json_decode(self.request.body)

        if data.get('angle') is not None:
            self.application.angle = data['angle']
        if data.get('throttle') is not None:
            self.application.throttle = data['throttle']
        if data.get('drive_mode') is not None:
            self.application.mode = data['drive_mode']
        if data.get('recording') is not None:
            self.application.recording = data['recording']
        if data.get('buttons') is not None:
            latch_buttons(self.application.buttons, data['buttons'])


class WsTest(RequestHandler):
    def get(self):
        data = {}
        self.render("templates/wsTest.html", **data)


class CalibrateHandler(RequestHandler):
    """ Serves the calibration web page"""
    async def get(self):
        await self.render("templates/calibrate.html")


def latch_buttons(buttons, pushes):
    """
    Latch button pushes
    buttons: the latched values
    pushes: the update value
    """
    if pushes is not None:
        #
        # we got button pushes.
        # - we latch the pushed buttons so we can process the push
        # - after it is processed we clear it
        #
        for button in pushes:
            # if pushed, then latch it
            if pushes[button]:
                buttons[button] = True


class WebSocketDriveAPI(tornado.websocket.WebSocketHandler):
    def check_origin(self, origin):
        return True

    def open(self):
        logger.info("New client connected")
        self.application.wsclients.append(self)

    def on_message(self, message):
        data = json.loads(message)
        self.application.angle = data.get('angle', self.application.angle)
        self.application.throttle = data.get('throttle', self.application.throttle)
        if data.get('drive_mode') is not None:
            self.application.mode = data['drive_mode']
            self.application.mode_latch = self.application.mode
        if data.get('recording') is not None:
            self.application.recording = data['recording']
            self.application.recording_latch = self.application.recording
        if data.get('buttons') is not None:
            latch_buttons(self.application.buttons, data['buttons'])

    def on_close(self):
        logger.info("Client disconnected")
        self.application.wsclients.remove(self)


class WebSocketTuningAPI(tornado.websocket.WebSocketHandler):
    """
    WebSocket for runtime tuning of the line follower (HSV, PID, throttle,
    scan region). Clients receive `{type: 'snapshot', tuning, seq}` on
    connect and after every accepted update. Clients send
    `{set: {key: value, ...}}` to mutate.
    """
    _RATE_LIMIT_S = 0.030  # drop bursts faster than ~33 Hz per client

    def check_origin(self, origin):
        return True

    def open(self):
        self._last_msg_ts = 0.0
        self.application.wsTuningClients.append(self)
        logger.info("[tuning] client connected (clients=%d)",
                    len(self.application.wsTuningClients))
        try:
            self.write_message(json.dumps({
                'type': 'snapshot',
                'tuning': self.application.tuning,
                'seq': self.application.tuning_seq,
            }))
            logger.info("[tuning] sent initial snapshot seq=%d",
                        self.application.tuning_seq)
        except Exception as e:
            logger.warning("Error writing tuning snapshot on open", exc_info=e)

    def on_message(self, message):
        now = time.time()
        if now - self._last_msg_ts < self._RATE_LIMIT_S:
            logger.info("[tuning] rate-limited drop (gap=%.3fs)",
                        now - self._last_msg_ts)
            return
        self._last_msg_ts = now
        logger.info("[tuning] recv: %s", message[:200])
        try:
            data = json.loads(message)
        except (TypeError, ValueError):
            logger.warning("[tuning] malformed JSON: %s", message[:100])
            return
        patch = data.get('set') or {}
        rejections = self.application.apply_tuning_patch(patch, origin=self)
        if rejections:
            logger.info("[tuning] rejections: %s", rejections)
            try:
                self.write_message(json.dumps({'type': 'rejected',
                                               'rejections': rejections}))
            except Exception:
                pass
        else:
            logger.info("[tuning] committed patch keys=%s seq=%d",
                        list(patch.keys()), self.application.tuning_seq)

    def on_close(self):
        try:
            self.application.wsTuningClients.remove(self)
        except ValueError:
            pass
        logger.info("[tuning] client disconnected (clients=%d)",
                    len(self.application.wsTuningClients))


class TuningSnippetHandler(RequestHandler):
    """GET /tuning/snippet — Python snippet for pasting into myconfig.py."""
    def get(self):
        self.set_header("Content-Type", "text/plain; charset=utf-8")
        self.write(_render_myconfig_snippet(self.application.tuning))


class TuningStateHandler(RequestHandler):
    """GET /tuning/state — JSON dump of current server-side tuning state.
    Useful for `curl` debugging when the UI looks wrong."""
    def get(self):
        self.set_header("Content-Type", "application/json")
        self.write(json.dumps({
            'tuning': self.application.tuning,
            'seq': self.application.tuning_seq,
            'clients': len(self.application.wsTuningClients),
        }))


class WebSocketCalibrateAPI(tornado.websocket.WebSocketHandler):
    def check_origin(self, origin):
        return True

    def open(self):
        logger.info("New client connected")

    def on_message(self, message):
        logger.info(f"wsCalibrate {message}")
        data = json.loads(message)
        if 'throttle' in data:
            print(data['throttle'])
            self.application.throttle = data['throttle']

        if 'angle' in data:
            print(data['angle'])
            self.application.angle = data['angle']

        if 'config' in data:
            config = data['config']
            if self.application.drive_train_type == "PWM_STEERING_THROTTLE" \
                or self.application.drive_train_type == "I2C_SERVO":
                if 'STEERING_LEFT_PWM' in config:
                    self.application.drive_train['steering'].left_pulse = config['STEERING_LEFT_PWM']

                if 'STEERING_RIGHT_PWM' in config:
                    self.application.drive_train['steering'].right_pulse = config['STEERING_RIGHT_PWM']

                if 'THROTTLE_FORWARD_PWM' in config:
                    self.application.drive_train['throttle'].max_pulse = config['THROTTLE_FORWARD_PWM']

                if 'THROTTLE_STOPPED_PWM' in config:
                    self.application.drive_train['throttle'].zero_pulse = config['THROTTLE_STOPPED_PWM']

                if 'THROTTLE_REVERSE_PWM' in config:
                    self.application.drive_train['throttle'].min_pulse = config['THROTTLE_REVERSE_PWM']

            elif self.application.drive_train_type == "MM1":
                if ('MM1_STEERING_MID' in config) and (config['MM1_STEERING_MID'] != 0):
                        self.application.drive_train.STEERING_MID = config['MM1_STEERING_MID']
                if ('MM1_MAX_FORWARD' in config) and (config['MM1_MAX_FORWARD'] != 0):
                        self.application.drive_train.MAX_FORWARD = config['MM1_MAX_FORWARD']
                if ('MM1_MAX_REVERSE' in config) and (config['MM1_MAX_REVERSE'] != 0):
                    self.application.drive_train.MAX_REVERSE = config['MM1_MAX_REVERSE']

    def on_close(self):
        logger.info("Client disconnected")


class VideoAPI(RequestHandler):
    '''
    Serves a MJPEG of the images posted from the vehicle.
    '''

    async def get(self):
        placeholder_image = utils.load_image_sized(
                        os.path.join(self.application.static_file_path,
                                     "img_placeholder.jpg"), 160, 120, 3)

        self.set_header("Content-type",
                        "multipart/x-mixed-replace;boundary=--boundarydonotcross")

        served_image_timestamp = time.time()
        my_boundary = "--boundarydonotcross\n"
        while True:

            interval = .005
            if served_image_timestamp + interval < time.time():
                #
                # if we have an image, then use it.
                # otherwise show placeholder
                #
                if hasattr(self.application, 'img_arr') and self.application.img_arr is not None:
                    img = utils.arr_to_binary(self.application.img_arr)
                else:
                    img = utils.arr_to_binary(placeholder_image)

                self.write(my_boundary)
                self.write("Content-type: image/jpeg\r\n")
                self.write("Content-length: %s\r\n\r\n" % len(img))
                self.write(img)
                served_image_timestamp = time.time()
                try:
                    await self.flush()
                except tornado.iostream.StreamClosedError:
                    pass
            else:
                await tornado.gen.sleep(interval)


class BaseHandler(RequestHandler):
    """ Serves the FPV web page"""
    async def get(self):
        data = {}
        await self.render("templates/base_fpv.html", **data)


class WebFpv(Application):
    """
    Class for running an FPV web server that only shows the camera in real-time.
    The web page contains the camera view and auto-adjusts to the web browser
    window size. Conjecture: this picture up-scaling is performed by the
    client OS using graphics acceleration. Hence a web browser on the PC is
    faster than a pure python application based on open cv or similar.
    """

    def __init__(self, port=8890):
        self.port = port
        this_dir = os.path.dirname(os.path.realpath(__file__))
        self.static_file_path = os.path.join(this_dir, 'templates', 'static')

        """Construct and serve the tornado application."""
        handlers = [
            (r"/", BaseHandler),
            (r"/video", VideoAPI),
            (r"/static/(.*)", StaticFileHandler,
             {"path": self.static_file_path})
        ]

        settings = {'debug': True}
        self.img_arr = None
        super().__init__(handlers, **settings)
        logger.info(f"Started Web FPV server. You can now go to "
                    f"{gethostname()}.local:{self.port} to view the car camera")

    def update(self):
        """ Start the tornado webserver. """
        asyncio.set_event_loop(asyncio.new_event_loop())
        self.listen(self.port)
        IOLoop.instance().start()

    def run_threaded(self, img_arr=None):
        self.img_arr = img_arr

    def run(self, img_arr=None):
        self.img_arr = img_arr

    def shutdown(self):
        pass


